services:

  odoo:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
      - "8072:8072"
    tty: true
    stdin_open: true
    volumes:
      - ./repositories:/home/odoo/src/repositories:rw,z
      - ./src:/home/odoo/src/user:rw,z
      - filestore:/home/odoo/data
    environment:
      PGHOST: db
      PGDATABASE: odoodb

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db:
  filestore:
