FROM ghcr.io/odoo-it/docker-odoo:{{ odoo_version }}-latest

# Install project requirements
RUN --mount=type=bind,src=requirements.txt,dst=$RESOURCES/requirements.txt \
    --mount=type=cache,target=/root/.cache/pip \
    pip install -r $RESOURCES/requirements.txt

# Copy sources
COPY --chown=odoo:odoo odoo $SOURCES/
COPY --chown=odoo:odoo repositories $SOURCES/repositories
COPY --chown=odoo:odoo addons $SOURCES/addons
RUN pip-install-odoo
